# Generated by Django 2.1 on 2019-01-30 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_switchgamelist_logged_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchGamePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('amount', models.CharField(max_length=12)),
                ('currency', models.CharField(max_length=8)),
                ('raw_value', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.SwitchGame')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchGameSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('amount', models.CharField(max_length=12)),
                ('currency', models.CharField(max_length=8)),
                ('raw_value', models.FloatField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.SwitchGame')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='switchgamesale',
            unique_together={('game', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='switchgameprice',
            unique_together={('game', 'country')},
        ),
    ]
